#!/sbin/sh

if [ -e /cache/recovery/boot ]
then

rm /cache/recovery/boot
touch /cache/recovery/enterrecovery

else

# trigger blue LED
echo '255' > /sys/class/leds/blue/brightness
# trigger button-backlight
echo '255' > /sys/class/leds/button-backlight/brightness

cat /dev/input/event1 > /dev/keycheck&
sleep 3

# trigger blue LED
echo '0' > /sys/class/leds/blue/brightness
# trigger button-backlight
echo '0' > /sys/class/leds/button-backlight/brightness

kill -9 $!

fi


if [ -s /dev/keycheck -o -e /cache/recovery/enterrecovery ]
then
# fixing CPU clocks to avoid issues in recovery
echo 1024000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 245760 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
# correct LCD-backlight brightness
echo '255' > /sys/class/leds/lcd-backlight/brightness

rm /cache/recovery/enterrecovery

mount -o remount,rw rootfs /
# shifting to "umount -l /partition" to avoid mounting issues in recovery
umount -l /system
umount -l /data
umount -l /cache
umount -l /sdcard
umount -l /mnt/sdcard
rm -r /sdcard
rm -r /not/sdcard
mkdir /sdcard
mkdir /tmp
rm /etc
mkdir /etc
cp /recovery.fstab /etc/recovery.fstab
mount /dev/block/mmcblk0p1 /sdcard
/sbin/recovery &
/sbin/adbd_rec recovery 
fi

# Offline charging
/system/bin/chargemon

#continue booting

